name: Build EXE (Debug Version)

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: CMake 配置
      run: cmake -B build -S . -A x64

    - name: 编译（显示详细日志）
      run: cmake --build build --config Release --verbose

    - name: 查看输出目录
      run: dir build/Release
