name: Nightly Build

on:
  schedule:
    - cron: '0 16 * * *'   # 北京时间每天 00:00
  workflow_dispatch:
permissions:
  contents: write 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: CMake
      run: cmake -B build -S . -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: 发布 Nightly
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: Nightly Build
        files: build/Release/*.exe
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
