name: Windows CMake Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v4
    - name: 配置 MSVC
      run: ilammy/msvc-dev-cmd@v1
    - name: 构建
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles"
        nmake
